services:
  postgres:
    image: postgres:15
    environment:
      # Airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      # Exploitation zone db
      POSTGRES_ANALYTICS_DB: analytics_db
      POSTGRES_ANALYTICS_USER: analytics_user
      POSTGRES_ANALYTICS_PASSWORD: analytics_password
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  redis:
    image: redis:7.2-bookworm
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=bdm
      - DOCKER_INFLUXDB_INIT_BUCKET=exploitation_zone_streaming_data
      - DOCKER_INFLUXDB_INIT_RETENTION=1h
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admintoken
    volumes:
      - influxdb-data:/var/lib/influxdb2
