services:
  jobmanager:
    image: apache/flink:1.19
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    entrypoint: ["/bin/sh", "-c", "chmod -R 777 /opt/flink/web-upload && exec /docker-entrypoint.sh jobmanager"]
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///opt/flink/checkpoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        rest.flamegraph.enabled: true
        web.upload.dir: /opt/flink/web-upload
        web.submit.enable: false
    volumes:
      - flink-checkpoints:/opt/flink/checkpoints
      - flink-usrlib:/opt/flink/usrlib
      # Using a bind mount with explicit permissions for web-upload directory
      - ./flink-web-upload:/opt/flink/web-upload
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/overview" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  taskmanager:
    image: apache/flink:1.19
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        state.backend: filesystem
        state.checkpoints.dir: file:///opt/flink/checkpoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
    volumes:
      - flink-checkpoints:/opt/flink/checkpoints
      - flink-usrlib:/opt/flink/usrlib

  bitcoin-aggregator:
    build:
      context: ../bdm/processing/streaming/bitcoin_aggregator
      dockerfile: Dockerfile
    container_name: bitcoin-aggregator
    environment:
      - KAFKA_ENDPOINT=kafka:9092
      - KAFKA_TOPIC=btc_usdt
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=landing-zone
    depends_on:
      - jobmanager
      - taskmanager
      - kafka
      - minio
