{
 "title": "Finazon Stream Dashboard",
 "tags": [
  "finazon",
  "streaming",
  "stocks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Stream Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"exploitation_zone_streaming_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"vwap_1min\")\n  |> keep(columns: [\"symbol\", \"data_source\"])\n  |> group(columns: [\"symbol\", \"data_source\"])\n  |> distinct(column: \"symbol\")"
    }
   ]
  },
  {
   "title": "Real-Time Ticks Ms Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"exploitation_zone_streaming_data\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"hot_path_ticks\")\n  |> filter(fn: (r) => r._field == \"latency_ms\")\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Real-Time Asset Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"exploitation_zone_streaming_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"hot_path_ticks\")\n  |> filter(fn: (r) => r._field == \"price\")\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "VWAP (Warm Path)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"exploitation_zone_streaming_data\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"vwap_1min\")\n  |> filter(fn: (r) => r._field == \"vwap\")\n  |> group(columns: [\"symbol\"])"
    }
   ]
  }
 ]
}